# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

include(global_macros)

# aka debian:9 (released June '17)
FROM debian:stretch

ENV DEBIAN_FRONTEND=noninteractive \
    DXT_ENVIRONMENT=debian-minimal

# we require stretch-backports for some packages (see below), but we only allow them in manual installs
# the upgrade should thus be a noop
# locale is mainly required for the interactive session
RUN APT_UPDATE APT_REDIRECT && \
    apt-get upgrade -qqy --no-install-recommends APT_REDIRECT && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen && \
    APT_INSTALL locales APT_REDIRECT && \
    export LANG=en_US.UTF-8 && \
    dpkg-reconfigure locales && \
    echo "Package: *" >> /etc/apt/preferences.d/stretch-backports && \
    echo "Pin: release a=stretch-backports" >> /etc/apt/preferences.d/stretch-backports && \
    echo "Pin-Priority: 200" >> /etc/apt/preferences.d/stretch-backports && \
    echo "deb http://deb.debian.org/debian stretch-backports main contrib non-free" > /etc/apt/sources.list.d/stretch-backports.list && \
    echo "deb http://deb.debian.org/debian/ stretch contrib non-free" > /etc/apt/sources.list.d/stretch-nonfree.list && \
    APT_UPDATE APT_REDIRECT && \
    APT_INSTALL automake bison build-essential cmake flex gfortran git libboost-system-dev \
                libboost-thread-dev libboost-filesystem-dev libboost-date-time-dev \
                libboost-timer-dev libboost-chrono-dev libsuperlu-dev libtool \
                pkg-config python3 python3-dev libgraphviz-dev python3-tk \
                python3-pip python3-virtualenv unzip virtualenv wget libopenblas-dev \
                ca-certificates wget sudo cmake cmake-curses-gui gosu APT_REDIRECT && \
    apt-get autoremove -y APT_REDIRECT && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://github.com/dune-community/cli-setup && \
    cd cli-setup && \
    cmake . && make install && cd .. && rm -rf cli-setup

ADD entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

include(labels)
