# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Rene Milk       (2017)
#   Felix Schindler (2017)

FROM dunecommunity/arch-minimal

ENV DXT_ENVIRONMENT arch-full

RUN ${PACMAN_UPDATE} && \
    ${PACMAN_INSTALL} alberta-wo-fem eigen gcc-fortran lapacke intel-tbb openmpi

include(labels)

# clean up, there might be some leftovers
RUN pacman -Rns --noconfirm $(pacman -Qtdq) || echo "no orphans present"
RUN pacman -Sc --noconfirm || echo "no cache to clear"
