# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

include(minimal)
include(interactive)

RUN echo 'export PATH=/usr/lib64/openmpi/1.4-gcc/bin:$PATH' > /opt/openmpi-1.4.activate.sh && \
    echo 'export LD_LIBRARY_PATH=/usr/lib64/openmpi/1.4-gcc/lib:$LD_LIBRARY_PATH' >> /opt/openmpi-1.4.activate.sh && \
    echo 'export PATH=${PATH/\/usr\/lib64\/openmpi\/1.4-gcc\/bin:/}' > /opt/openmpi-1.4.deactivate.sh && \
    echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH/\/usr\/lib64\/openmpi\/1.4-gcc\/lib:/}' >> /opt/openmpi-1.4.deactivate.sh

RUN yum -y install blas-devel doxygen gdb lapack-devel openmpi-devel && \
    cd /usr/local/bin && \
    for ii in mpic++ mpicc mpiCC mpicxx; do ln -s $(which ccache) $ii; done && \
    yum clean all

ENV DXT_ENVIRONMENT manylinux-full

include(labels)
