# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

FROM markrwilliams/manylinux2:x86_64

# locale is mainly required for the interactive session
RUN localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 && \
    localedef -v -c -i de_DE -f UTF-8 de_DE.UTF-8 || \
    echo ""

# sudo and gosu are only required for the interactive session
# for gosu see https://github.com/pymor/Dockerfiles/blob/master/base/xenial/Dockerfile.in
RUN set -x && \
    export GOSU_VERSION=1.9 && \
    yum -y install epel-release && \
    yum -y install sudo wget dpkg gnupg2 && \
    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" && \
    wget -O /usr/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" && \
    wget -O /tmp/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" && \
    export GNUPGHOME="$(mktemp -d)" && \
    gpg2 --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && \
    gpg2 --batch --verify /tmp/gosu.asc /usr/bin/gosu && \
    rm -r "$GNUPGHOME" /tmp/gosu.asc && \
    chmod +x /usr/bin/gosu && \
    gosu nobody true

# the bare minimum, part 1 (what we can install from repos)
RUN yum -y install flex git libtool pkgconfig cmake3 devtoolset-7-all boost148

# create PATH files for all present python versions and install virtualenv
RUN cd /opt/python && \
    for ii in $(ls -d *); do \
      echo "export PATH=/opt/python/$ii/bin:"'$PATH' > /opt/python/${ii}.activate.sh && \
      echo "export LD_LIBRARY_PATH=/opt/$ii/lib:"'$LD_LIBRARY_PATH' >> /opt/python/${ii}.activate.sh && \
      echo "export PKG_CONFIG_PATH=/opt/$ii/lib/pkgconfig:"'$PKG_CONFIG_PATH' >> /opt/python/${ii}.activate.sh && \
      echo 'export PATH=${PATH/\/opt\/python\/'"$ii"'\/bin:/}' > /opt/python/${ii}.deactivate.sh && \
      echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH/\/opt\/'"$ii"'\/lib:/}' >> /opt/python/${ii}.deactivate.sh && \
      echo 'export PKG_CONFIG_PATH=${PKG_CONFIG_PATH/\/opt\/'"$ii"'\/lib\/pkgconfig:/}' >> /opt/python/${ii}.deactivate.sh && \
      source /opt/python/${ii}.activate.sh && \
      pip install virtualenv; \
      source /opt/python/${ii}.deactivate.sh; done

# clean up, there might be some leftovers
RUN yum -y remove dpkg texinfo && \
    yum clean all

ADD entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ENV DXT_ENVIRONMENT manylinux-minimal

include(labels)
