# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Rene Milk       (2017)
#   Felix Schindler (2017)

include(global_macros)

FROM dunecommunity/debian-minimal

ENV DEBIAN_FRONTEND=noninteractive \
    DXT_LIBCLANG_SO=/usr/lib/llvm-${CLANG_VERSION}/lib/libclang.so.1 \
    DXT_ENVIRONMENT=debian-full

RUN APT_UPDATE APT_REDIRECT && \
    APT_INSTALL doxygen libc++-dev clang-${CLANG_VERSION} clang-format-${CLANG_VERSION} clang-tidy-${CLANG_VERSION} \
        libalberta-dev libeigen3-dev libscotchmetis-dev libscotchparmetis-dev libsuitesparse-dev libtbb-dev \
        libmumps-scotch-dev python-clang-${CLANG_VERSION} \
        ninja-build openmpi-common openmpi-bin libqhull-dev liblpsolve55-dev liblapacke-dev ssh APT_REDIRECT && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${CLANG_VERSION} 100 && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

include(labels)
