# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Rene Milk       (2017)
#   Felix Schindler (2017)

FROM dunecommunity/debian-minimal

ENV DEBIAN_FRONTEND=noninteractive \
    DXT_LIBCLANG_SO=/usr/lib/llvm-3.9/lib/libclang.so.1 \
    DXT_EXTERNAL_LIBS=debian__full

RUN ${APT_UPDATE} && \
    ${APT_INSTALL} doxygen libc++-dev clang-3.9 clang-format-3.9 clang-tidy-3.9 \
        libalberta-dev libeigen3-dev libscotchmetis-dev libscotchparmetis-dev libsuitesparse-dev libtbb-dev \
        ninja-build openmpi-common openmpi-bin libqhull-dev liblpsolve55-dev liblapacke-dev ssh && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 100 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 100 && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

include(labels)
