# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

FROM archlinux/base

ENV PACMAN_INSTALL="pacman -S --noconfirm " \
    PACMAN_UPDATE="pacman -Syuu --noconfirm " \
    DXT_ENVIRONMENT=arch-minimal \
    DXT_DOCKER=1

# init and update
RUN pacman -Sc --noconfirm && \
    ${PACMAN_UPDATE} && \
    ${PACMAN_INSTALL} awk reflector && \
    reflector --country 'Germany' --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist && \
    ${PACMAN_UPDATE} && \
    mkdir -p /root/.gnupg/dirmngr-cache.d && \
    chmod 700 /root/.gnupg && \
    touch /root/.gnupg/dirmngr_ldapservers.conf && \
    echo "keyserver hkps://hkps.pool.sks-keyservers.net:443" > /root/.gnupg/dirmngr.conf && \
    gpg -k && \
    dirmngr < /dev/null && \
    pacman-key --init && \
    pacman-key --populate archlinux

RUN echo "" >> /etc/pacman.conf && \
    echo "[aur]" >> /etc/pacman.conf && \
    echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf && \
    echo "Server = http://repos.schindlerfamily.de/arch/aur" >> /etc/pacman.conf && \
    echo "" >> /etc/pacman.conf && \
    ${PACMAN_UPDATE}

# locale is mainly required for the interactive session
RUN ${PACMAN_UPDATE} && \
    ${PACMAN_INSTALL} glibc sed && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen && \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
    echo "LC_COLLATE=C" > /etc/locale.conf && \
    echo "LC_ALL=en_US.UTF-8" > /etc/locale.conf && \
    echo "LC_TIME=de_DE.UTF-8" > /etc/locale.conf

# the bare minimum
RUN ${PACMAN_UPDATE} && \
    ${PACMAN_INSTALL} base-devel make blas boost boost-libs git cmake python2 python python-pip \
    python2-pip python-setuptools python2-setuptools python2-virtualenv python-virtualenv \
    sudo suexec superlu unzip wget gcc-fortran
include(dune_cli)

RUN cd /usr/local/bin && ln -s $(which su-exec) gosu && ln -s /usr/bin/vendor_perl/ack .

# clean up, there might be some leftovers
RUN pacman -Rns --noconfirm $(pacman -Qtdq) || echo "no orphans present"
RUN pacman -Sc --noconfirm || echo "no cache to clear"

ADD entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

include(labels)

