# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Rene Milk (2017)

FROM dunecommunity/arch-full

include(environment)

RUN ${PACMAN_UPDATE} && \
    ${PACMAN_INSTALL} ninja texlive-bin texlive-core rsync openssh doxygen && \
    mkdir -p ~/.ssh/ && ssh-keyscan -H github.com >> ~/.ssh/known_hosts && \
    git config --global push.default simple

ADD entrypoint.bash /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/entrypoint.bash"]

include(labels)
