# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

include(global_macros)

include(minimal)

ENV DEBIAN_FRONTEND=noninteractive \
    DXT_ENVIRONMENT=debian-minimal

RUN APT_UPDATE APT_REDIRECT && \
    APT_INSTALL \
        doxygen texlive-latex-base python3-sphinx python-sphinx \
        inkscape texlive-latex-extra APT_REDIRECT && \
    apt-get autoremove -y APT_REDIRECT && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#include(standardese)
include(labels)
