# This file is part of the dune-community/Dockerfiles project:
#   https://github.com/dune-community/Dockerfiles
# Copyright 2017 dune-community/Dockerfiles developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
# Authors:
#   Felix Schindler (2017)
#   Rene Milk       (2017)

FROM dunecommunity/debian-minimal

ENV DEBIAN_FRONTEND=noninteractive \
    DXT_ENVIRONMENT=debian-minimal

RUN ${APT_UPDATE} && \
    ${APT_INSTALL} \
        texlive-latex-base python3-sphinx python-sphinx \
        inkscape texlive-latex-extra && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

include(labels)
